input_polygons:
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_waterdeel.sqlite
      - c:/gebruikers/stan_/data/sqlite/bgt_ondersteunendwaterdeel.sqlite
    uniqueid: gml_id
    lifting: Water
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_onbegroeidterreindeel.sqlite
    uniqueid: gml_id
    lifting: Terrain
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_wegdeel.sqlite
      - c:/gebruikers/stan_/data/sqlite/bgt_ondersteunendwegdeel.sqlite
    uniqueid: gml_id
    lifting: Road
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_pand.sqlite
    uniqueid: gml_id
    lifting: Building
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_begroeidterreindeel.sqlite
    uniqueid: gml_id
    lifting: Forest
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_scheiding.sqlite
      - c:/gebruikers/stan_/data/sqlite/bgt_kunstwerkdeel.sqlite
      - c:/gebruikers/stan_/data/sqlite/bgt_overigbouwwerk.sqlite
    uniqueid: gml_id
    lifting: Separation
    height_field: relatievehoogteligging
  - datasets: 
      - c:/gebruikers/stan_/data/sqlite/bgt_overbruggingsdeel.sqlite
    uniqueid: gml_id
    lifting: Bridge/Overpass
    height_field: relatievehoogteligging
    handle_multiple_heights: true

lifting_options: 
  Building:
    height_roof: percentile-90
    height_floor: percentile-10
    lod: 1
  Terrain:
    simplification: 10
  Forest:
    simplification: 10
  Water:
    height: percentile-10
  Road:
    height: percentile-50
  Separation:
    height: percentile-80
  Bridge/Overpass:
    height: percentile-50

input_elevation:
  - datasets:
      - c:/gebruikers/stan_/data/nieuwstraat.las
    omit_LAS_classes:
      - 1 # unclassified
    thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5

output: 
  format: OBJ
  # format: CityGML
  building_floor: false
  vertical_exaggeration: 0
